name: team_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.1
  dropdown_search: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/h1.jpeg"

flutter:

  uses-material-design: true


